spring.application.name=backend
#spring.data.mongodb.uri=mongodb+srv://kanchan_agarwal:db_chat_app@cluster0.anjnjak.mongodb.net/chatapp?retryWrites=true&w=majority&appName=Cluster0
spring.mongodb.uri=mongodb+srv://kanchan_agarwal:250719%40CodingLearn@cluster0.anjnjak.mongodb.net/chatapp?retryWrites=true&w=majority&appName=Cluster0